apiVersion: v1
kind: Service
metadata:
  name: test-client-service
  labels:
    group: qa
spec:
  ports:
  - port: 8099
    nodePort: 30899
    targetPort: 8099
    name: jenkins
  - port: 5900
    nodePort: 30590
    targetPort: 5900
    name: vnc
  type: NodePort
  selector:
    group: qa
